voting_lectures/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import webapp.views

urlpatterns = [
    # Examples:
    # url(r'^$', 'voting_lectures.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', webapp.views.index, name="index"),
    url(r'^(?P<lecture_id>[0-9]+)/students/$', webapp.views.get_students, name="students"),
    url(r'^(?P<lecture_id>[0-9]+)/sheets/$', webapp.views.sheets, name="sheets"),
    url(r'^(?P<lecture_id>[0-9]+)/student_list/$', webapp.views.student_list, name="student_list"),
    url(r'^(?P<lecture_id>[0-9]+)/frs_import_start/$', webapp.views.frs_import_start, name="frs_import_start"),
    url(r'^(?P<lecture_id>[0-9]+)/lecture_rights/$', webapp.views.lecture_rights, name="lecture_rights"),
    url(r'^(?P<sheet_id>[0-9]+)/voting_list/$', webapp.views.voting_list, name="voting_list"),
    url(r'^exam/(?P<exam_id>[0-9]+)/$', webapp.views.exam, name="exam"),
    url(r'^students/$', webapp.views.student_suggestions, name="student_suggestions"),
    url(r'^student-query/$', webapp.views.query_user, name="query_user"),

    url(r'^actions/add_student_to_lecture/$', webapp.views.add_student_to_lecture, name="add_student_to_lecture"),
    url(r'^actions/add_student_to_group/$', webapp.views.add_student_to_group, name="add_student_to_group"),
    url(r'^actions/remove_student/$', webapp.views.remove_student, name="remove_student"),
    url(r'^actions/update_group_assignment/$', webapp.views.update_group_assignment, name="update_group_assignment"),
    url(r'^actions/update_exam_assignment/$', webapp.views.update_exam_assignment, name="update_exam_assignment"),
    url(r'^actions/submit_comment/$', webapp.views.submit_comment, name="submit_comment"),
    url(r'^actions/get_lecture_comments/$', webapp.views.get_lecture_comments, name="get_lecture_comments"),
    url(r'^actions/create_sheet/$', webapp.views.create_sheet, name="create_sheet"),
    url(r'^actions/create_task/$', webapp.views.create_task, name="create_task"),
    url(r'^actions/update_tick_status/$', webapp.views.update_tick_status, name="update_tick_status"),
    url(r'^actions/update_exam_student_points/$', webapp.views.update_exam_student_points, name="update_exam_student_points"),
    url(r'^actions/update_exam_points/$', webapp.views.update_exam_points, name="update_exam_points"),
    url(r'^actions/update_exam_config/$', webapp.views.update_exam_config, name="update_exam_config"),
    url(r'^actions/update_marks/$', webapp.views.update_marks, name="update_marks"),
    url(r'^actions/frs_import_process/$', webapp.views.frs_import_process, name="frs_import_process"),
    url(r'^actions/change_semester/(?P<semester_id>[0-9]+)/$', webapp.views.change_semester, name="change_semester"),
    url(r'^actions/get_mail_list/lecture/(?P<lecture_id>[0-9]+)/$', webapp.views.get_mail_list, name="get_mail_list_lecture"),
    url(r'^actions/get_mail_list/group/(?P<group_id>[0-9]+)/$', webapp.views.get_mail_list, name="get_mail_list_group"),
    url(r'^actions/get_mail_list/exam/(?P<exam_id>[0-9]+)/$', webapp.views.get_mail_list, name="get_mail_list_exam"),
    url(r'^actions/create_lecture/(?P<name>[^/]+)/$', webapp.views.create_lecture, name="create_lecture"),
    url(r'^actions/create_group/(?P<lecture_id>[0-9]+)/(?P<desc>[^/]+)/$', webapp.views.create_group, name="create_group"),
    url(r'^actions/create_exam/(?P<lecture_id>[0-9]+)/(?P<datestr>[^/]+)/$', webapp.views.create_exam, name="create_exam"),
    url(r'^actions/set_lecture_rights/(?P<lecture_id>[0-9]+)/(?P<user_id>[0-9]+)/(?P<subset>[^/]+)/(?P<value>[01])/$', webapp.views.set_lecture_rights, name="set_lecture_rights"),
    url(r'^actions/check_permissions/$', webapp.views.check_permissions, name="check_permissions"),
    url(r'^export/lecture/(?P<lecture_id>[0-9]+).xlsx$', webapp.views.lecture_excel_export, name="lecture_excel_export"),
]

webapp/models.py
from __future__ import print_function, division, unicode_literals, absolute_import, generators

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from guardian.shortcuts import assign_perm
from django.contrib.auth.models import Group as SysGroup

import six
import json

# Create your models here.

class Student(models.Model):
    uid = models.CharField(max_length=64, null=True, unique=True)
    given_name = models.CharField(max_length=64, null=True)
    surname = models.CharField(max_length=64, null=True)
    mail = models.EmailField(null=True)
    custom_mail = models.EmailField(null=True)
    matrikel_number = models.IntegerField(null=True)

    class Meta:
        ordering = ["surname", "given_name", "uid"]

    def __str__(self):
        if six.PY2:
            return self.__unicode__().encode("ascii", "ignore")
        return self.__unicode__()

    def __unicode__(self):
        return "{} {} [{}]".format(self.given_name, self.surname, self.uid)

    def get_mail(self):
        if self.custom_mail:
            return self.custom_mail
        return self.mail

    def get_jsonable(self, lecture=None):
        groups = self.group_set.all()
        exams = self.exam_set.all()
        comment = None
        admission = None
        if lecture:
            groups = groups.filter(lecture=lecture)
            exams = exams.filter(lecture=lecture)
            try:
                sl_map = StudentLectureMap.objects.get(student=self, lecture=lecture)
                comment = sl_map.comment
            except StudentLectureMap.DoesNotExist:
                pass
        return {
            "pk": self.pk,
            "id": self.id,
            "uid": self.uid,
            "given_name": self.given_name,
            "surname": self.surname,
            "mail": self.custom_mail if self.custom_mail else self.mail,
            "group_ids": list(groups.values_list("pk", flat=True)),
            "exam_ids": list(exams.values_list("pk", flat=True)),
            "comment": comment,
        }


class Semester(models.Model):
    year = models.IntegerField()
    winter = models.BooleanField()

    def get_semester(self, short=False):
        if short:
            if self.winter:
                return "{}/{}".format(self.year, (self.year+1) % 100)
            return "{}".format(self.year)

        if self.winter:
            return "WiSe {}/{}".format(self.year, (self.year+1) % 100)
        return "SoSe {}".format(self.year)

    def __str__(self):
        return self.get_semester()

    class Meta:
        ordering = ["-year", "-winter"]


class StudentLectureMap(models.Model):
    student = models.ForeignKey(Student)
    lecture = models.ForeignKey("Lecture")
    comment = models.TextField(null=True, blank=True)
    admission = models.NullBooleanField(default=None)
    sub_group = "admin"


class Lecture(models.Model):
    semester = models.ForeignKey(Semester)
    english = models.BooleanField(default=False)
    symbol = models.CharField(max_length=8)
    name = models.CharField(max_length=64)
    sub_group = "admin"

    min_voting_ratio = models.FloatField(default=0.66)
    min_presentations = models.IntegerField(default=2)

    participants = models.ManyToManyField(Student, blank=True, through=StudentLectureMap)

    def get_full_name(self):
        return "{} - {}".format(self.name, self.semester.get_semester())

    def get_short_name(self):
        return "{} {}".format(self.symbol, self.semester.get_semester(short=True))

    def next_sheet_number(self):
        if not self.sheet_set.all().exists():
            return 1
        return max(self.sheet_set.all().values_list("number", flat=True)) + 1

    def next_task_number(self):
        query = Task.objects.filter(sheet__lecture_id=self.id).exclude(number=None)
        if not len(query):
            return 1
        return max(query.values_list("number", flat=True)) + 1

    def __str__(self):
        if six.PY2:
            return self.__unicode__().encode("ascii", "ignore")
        else:
            return self.__unicode__()

    def __unicode__(self):
        return self.get_full_name()

    def create_groups(self):
        groups = ["admin", "exercise", "exam"]
        group_objs = dict()
        for g in groups:
            group_name = "lecture_{}_{}".format(self.id, g)
            group, created = SysGroup.objects.get_or_create(name=group_name)

            if created:
                group.save()
            group_objs[g] = group

            if g == "admin":
                assign_perm("webapp.delete_lecture", group)
                assign_perm("webapp.delete_studentlecturemap", group)
                assign_perm("change_lecture", group, self)
                assign_perm("delete_lecture", group, self)
            elif g == "exercise" or g == "admin":
                assign_perm("webapp.delete_group", group)
                assign_perm("webapp.delete_sheet", group)
                assign_perm("webapp.delete_task", group)
                assign_perm("webapp.delete_tickedtask", group)
            elif g == "exam" or g == "admin":
                assign_perm("webapp.delete_exam", group)
                assign_perm("webapp.delete_studentexam", group)
        return group_objs

    def assign_related_object(self, obj):
        name = obj._meta.model_name
        group_name = "lecture_{}_{}".format(self.id, obj.sub_group)
        group, created = SysGroup.objects.get_or_create(name=group_name)

        if created:
            self.create_groups()
            group, _ = SysGroup.objects.get_or_create(name=group_name)

        assign_perm("change_{}".format(name), group, obj)
        assign_perm("delete_{}".format(name), group, obj)

    def can_see(self, user):
        return self.can_exercise(user) or self.can_exam(user) or self.can_admin(user)

    def can_exam(self, user):
        return self.has_lecture_perm(user, "exam")

    def can_exercise(self, user):
        return self.has_lecture_perm(user, "exercise")

    def can_admin(self, user):
        return self.has_lecture_perm(user, "admin")

    def has_lecture_perm(self, user, perm):
        return user.groups.filter(name="lecture_{}_{}".format(self.id, perm)).exists()

    class Meta:
        ordering = ["semester", "name"]


class Group(models.Model):
    lecture = models.ForeignKey(Lecture)
    desc = models.CharField(max_length=64)
    students = models.ManyToManyField(Student, blank=True)
    sub_group = "exercise"

    def __str__(self):
        return "{}  ---  {}".format(self.lecture.get_short_name(), self.desc)

    class Meta:
        ordering = ["lecture"]


class Sheet(models.Model):
    lecture = models.ForeignKey(Lecture)
    number = models.IntegerField(null=True)
    last_sheet = models.ForeignKey("self", null=True, blank=True)
    sub_group = "exercise"

    def __str__(self):
        return "{} - Blatt {}".format(self.lecture.get_short_name(), self.number)


class TickedTask(models.Model):
    student = models.ForeignKey(Student)
    task = models.ForeignKey("Task")
    presented = models.BooleanField(default=False)
    excused = models.BooleanField(default=False)
    sub_group = "exercise"


class Task(models.Model):
    sheet = models.ForeignKey(Sheet)
    number = models.IntegerField(null=True, blank=True)
    label = models.CharField(max_length=16, null=True, blank=True)
    optional = models.BooleanField(default=False)
    sub_group = "exercise"

    students_set = models.ManyToManyField(Student, through=TickedTask)

    def get_label(self):
        return self.label if self.label else self.number

    def __str__(self):
        return "{}: Aufgabe {}".format(self.sheet, self.get_label())


class StudentExam(models.Model):
    student = models.ForeignKey(Student)
    exam = models.ForeignKey("Exam")
    points = models.TextField(default="[]")
    mark = models.FloatField(blank=True, null=True)
    lsf_group = models.IntegerField(default=0)
    sub_group = "exam"

    def point_list_parsed(self):
        number_of_tasks = self.exam.number_of_tasks
        points_list = json.loads(self.points)
        while len(points_list) < number_of_tasks:
            points_list.append(0)
            self.points = json.dumps(points_list)
            self.save()
        return points_list[:number_of_tasks]

    class Meta:
        ordering = ["exam", "student"]


class Exam(models.Model):
    lecture = models.ForeignKey(Lecture)
    date = models.DateField()
    students = models.ManyToManyField(Student, blank=True, through=StudentExam)
    number_of_tasks = models.IntegerField(default=1)
    point_list = models.TextField(default="[]")
    point_round = models.FloatField(default=0.5)
    rating_max_points = models.FloatField(default=0)
    rating_points_diff_ratio = models.FloatField(default=5)
    sub_group = "exam"

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        if six.PY2:
            return self.__unicode__().encode("ascii", "ignore")
        else:
            return self.__unicode__()

    def __unicode__(self):
        return "Exam [{}] - {}".format(self.date, self.lecture)

    def point_list_parsed(self):
        return json.loads(self.point_list)[:self.number_of_tasks]

    def rating_points_diff(self):
        return self.rating_max_points * self.rating_points_diff_ratio / 100

webapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}Votierungssystem{% endblock %}</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static "css/site.css" %}">
    <link rel="stylesheet" type="text/css" media="print" href="{% static "css/print.css" %}" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-lg-2 hidden-print">
                <div class="panel-group" id="lecturesAccordion" role="tablist" aria-multiselectable="true">

                    <div class="panel panel-primary">
                        <div class="panel-heading" role="tab" id="headingSemester">
                            <h3 class="panel-title">
                                <a data-toggle="collapse" data-parent="#lecturesAccordion"
                                   href="#collapseSemester"
                                   aria-expanded="false"
                                   aria-controls="collapseSemester">
                                    {% if current_semester %}
                                        {{ current_semester }}
                                    {% else %}
                                        Semester
                                    {% endif %}
                                </a>
                            </h3>
                        </div>
                        <div id="collapseSemester" class="panel-collapse collapse" role="tabpanel"
                             aria-labelledby="headingSemester">
                            <ul class="list-group">
                                {% for semester in semesters %}
                                    <a class="list-group-item" href="{% url "change_semester" semester.id%}">
                                        {{ semester }}
                                    </a>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                {% for l in lectures %}
                    <div class="panel panel-info">
                        <div class="panel-heading" role="tab" id="heading{{ l.id }}">
                            <h3 class="panel-title">
                                <a data-toggle="collapse" data-parent="#lecturesAccordion"
                                   href="#collapse{{ l.id }}"
                                   aria-expanded="{% if lecture.id == l.id %}true{% else %}false{% endif %}"
                                   aria-controls="collapse{{ l.id }}">
                                    {{ l.get_short_name }}
                                </a>
                                <a href="{% url "admin:webapp_lecture_change" l.id %}" class="pull-right">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </a>
                            </h3>
                        </div>
                        <div id="collapse{{ l.id }}" class="panel-collapse collapse {% if lecture.id == l.id %}in{% endif %}" role="tabpanel"
                             aria-labelledby="heading{{ l.id }}">
                            <ul class="list-group">
                                {% if l.is_exercise %}
                                    {% for s in l.sheet_set.all %}
                                        <a class="list-group-item" href="{% url "voting_list" s.pk %}">
                                            <span class="glyphicon glyphicon-file"></span>&nbsp;Blatt {{ s.number }}
                                        </a>
                                    {% endfor %}
                                    <a class="list-group-item" href="{% url "sheets" l.id %}">
                                        <span class="glyphicon glyphicon-duplicate"></span>&nbsp;&Uuml;bungsbl&auml;tter
                                    </a>
                                {% endif %}
                                {% if l.is_exam %}
                                    {% for e in l.exam_set.all %}
                                        <a class="list-group-item" href="{% url "exam" e.pk %}">
                                            <span class="glyphicon glyphicon-pencil"></span>&nbsp;Exam {{ e.date }}
                                        </a>
                                    {% endfor %}
                                {% endif %}
                                {% if l.is_exercise or l.is_exam %}
                                    <a class="list-group-item" href="{% url "students" l.id %}">
                                        <span class="glyphicon glyphicon-user"></span>&nbsp;Studenten</a>
                                {% endif %}
                                {% if l.is_exercise %}
                                    <a class="list-group-item" href="{% url "frs_import_start" l.id %}">
                                        <span class="glyphicon glyphicon-import"></span>&nbsp;FRS-Import
                                    </a>
                                {% endif %}
                                {% if l.is_admin %}
                                    <a class="list-group-item" href="{% url "lecture_excel_export" l.id %}">
                                        <span class="glyphicon glyphicon-save-file"></span>&nbsp;Export
                                    </a>
                                    <a class="list-group-item" href="{% url "lecture_rights" l.id %}">
                                        <span class="glyphicon glyphicon-eye-open"></span>&nbsp;Zugriffsrechte
                                    </a>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                {% endfor %}
                {% if can_create_lectures %}
                    <div class="panel panel-success">
                        <div class="panel-heading" role="tab">
                            <h3 class="panel-title">
                                <a id="create_lecture_link" href="#">
                                    <span class="glyphicon glyphicon-plus"></span> Neue Vorlesung
                                </a>
                            </h3>
                        </div>
                    </div>
                {% endif %}
                </div>
            </div>
            <div class="col-sm-9 col-lg-10 col-print-12">{% block content %}Content{% endblock %}</div>
        </div>
    </div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static "js/jquery.autocomplete.min.js" %}"></script>
    <script src="{% static "js/jquery.tablesorter.min.js" %}"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="http://code.highcharts.com/highcharts-more.js"></script>
    <script src="{% static "js/voting.js" %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

webapp/templates/index.html
{% extends "base.html" %}

{% block title %}
    Welcome
{% endblock %}

{% block content %}
    <h2>Last changes</h2>
<pre>
{{ gitlog }}
</pre>
{% endblock %}

webapp/templates/list.html
{% extends "base.html" %}

{% block title %}
    {{ lecture.get_full_name }} -
    {% if lecture.english %}Sheet{% else %}Blatt{% endif %}
    {{ sheet.number }}
{% endblock %}

{% block content %}
    <h1 class="hidden-print">{{ lecture.get_full_name }}</h1>

    {% with sheet.last_sheet.task_set.all as last_sheet_tasks %}
    {% with sheet.task_set.all as sheet_tasks %}


    {% for group in lecture.group_set.all %}
        <h2>
            <span class="visible-print-inline">{{ lecture.get_short_name }} - </span>
            {{ group.desc }}
        </h2>

        <table class="table tick-list{% if not forloop.last %} break-after{% endif %}">
            <thead>
                <tr>
                    <th colspan="2">&nbsp;</th>
                    {% if last_sheet_tasks %}
                        <th class="text-center" colspan="{{ last_sheet_tasks|length }}">
                            {% if lecture.english %}Sheet{% else %}Blatt{% endif %} {{ sheet.last_sheet.number }}
                        </th>
                    {% endif %}
                    <th class="text-center" colspan="{{ sheet_tasks|length }}">
                        {% if lecture.english %}Sheet{% else %}Blatt{% endif %} {{ sheet.number }}
                    </th>
                    <th colspan="3">&nbsp;</th>
                    <th class="hidden-print disable-click">
                        <label>
                            <input type="checkbox" class="print-comment-switch">
                            <span class="glyphicon glyphicon-print"></span>
                        </label>
                    </th>
                </tr>
                <tr>
                    <th>Name</th>
                    <th>{% if lecture.english %}Given Name{% else %}Vorname{% endif %}</th>
                    {% if last_sheet_tasks %}
                        {% for task in last_sheet_tasks %}
                            <th class="text-center">
                                {% if task.optional %}
                                    <em>{{ task.get_label }}</em>
                                {% else %}
                                    {{ task.get_label }}
                                {% endif %}
                            </th>
                        {% endfor %}
                    {% endif %}
                    {% for task in sheet_tasks %}
                        <th class="text-center">
                            {% if task.optional %}
                                <em>{{ task.get_label }}</em>
                            {% else %}
                                {{ task.get_label }}
                            {% endif %}
                        </th>
                    {% endfor %}

                    {% if lecture.english %}
                        <th class="text-center">Ticked&thinsp;/{{ max_tasks }}</th>
                        <th class="text-center">Presented</th>
                        <th class="text-center">Ratio</th>
                        <th class="hidden-print printable-comment">Comment</th>
                    {% else %}
                        <th class="text-center">Votiert&thinsp;/{{ max_tasks }}</th>
                        <th class="text-center">Pr&auml;sentiert</th>
                        <th class="text-center">Anteil</th>
                        <th class="hidden-print printable-comment">Kommentar</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for student in group.students.all %}
                    <tr>
                        <td>{{ student.surname }}</td>
                        <td>{{ student.given_name }}</td>

                        {% if last_sheet_tasks %}
                            {% for task in last_sheet_tasks %}
                                <td class="text-center">
                                    <span class="tick-view" data-student="{{ student.id }}" data-task="{{ task.id }}">
                                    </span>
                                </td>
                            {% endfor %}
                        {% endif %}
                        {% for task in sheet_tasks %}
                            <td class="text-center">
                                <input type="text" class="form-control hidden-print tick-input tabindex"
                                       data-student="{{ student.id }}" data-task="{{ task.id }}"
                                       maxlength="1">
                                <span class="tick-view hidden-print"
                                      data-student="{{ student.id }}" data-task="{{ task.id }}" data-toggle="">
                                </span>
                                <span class="glyphicon glyphicon-unchecked visible-print-inline"></span>
                            </td>
                        {% endfor %}
                        <td class="text-center">
                            <span class="tick-counter" data-field="ticked" data-student="{{ student.id }}"></span>
                            <span class="tick-counter" data-field="ticked_addon" data-student="{{ student.id }}"></span>
                        </td>
                        <td class="text-center">
                            <span class="tick-counter" data-field="presented" data-student="{{ student.id }}"></span>
                        </td>
                        <td class="text-center">
                            <span class="tick-counter" data-field="ratio" data-student="{{ student.id }}"></span>&thinsp;%
                        </td>
                        <td class="hidden-print printable-comment">
                            <input class="form-control hidden-print student-comment student-comment-{{ student.id }}"
                                   data-student="{{ student.id }}">
                            <span class="visible-print-inline student-comment-text-{{ student.id }}"
                                  data-student="{{ student.id }}" ></span>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endfor %}
    {% endwith %}
    {% endwith %}
{% endblock %}


{% block javascript %}
    <script>
        window.tasks_done = JSON.parse('{{ tasks_done_json|safe }}');
        window.line_length = {{ sheet.task_set.all.count }};
        window.get_lecture_comments({{ lecture.id }});
        window.lecture_id = {{ lecture.id }};
        window.update_tick_list();
    </script>
{% endblock %}

webapp/templates/sheets.html
{% extends "base.html" %}

{% block content %}
    <h1>&Uuml;bungsbl&auml;tter - {{ lecture.get_full_name }}</h1>
    {% for sheet in sheets %}
        <h2>Blatt {{ sheet.number }}
            <small>
                <a href="{% url "admin:webapp_sheet_change" sheet.id %}" class="">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
            </small>
        </h2>
        <ul>
            {% for task in sheet.task_set.all %}
                <li>Aufgabe:
                    {% if task.number %}{{ task.number }}{% endif %}
                    {% if task.label %}{{ task.label }}{% endif %}
                    {% if task.optional %}[optional]{% endif %}
                    <a href="{% url "admin:webapp_task_change" task.id %}" class="">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% endfor %}
    <form class="form" role="form" method="post" action="{% url "create_sheet" %}">
        {% csrf_token %}
        <input type="hidden" name="lecture_id" value="{{ lecture.id }}">
        <div class="input-group col-sm-6 col-md-4 col-lg-3">
            <span class="input-group-addon">Blatt Nr.:</span>
            <input type="number" class="form-control" placeholder="#" maxlength="3"
                   value="{{ lecture.next_sheet_number }}" name="number">
            <span class="input-group-btn">
                <input type="submit" class="btn btn-primary" type="button" value="erstellen">
            </span>
        </div>
    </form>
    {% if sheets %}
        <h2>Neue Aufgabe</h2>
        <form class="form-horizontal" role="form" method="post" action="{% url "create_task" %}">
            {% csrf_token %}
            <input type="hidden" name="sheet_id" value="{{ sheets.last.pk }}">
            <div class="form-group">
                <label for="task_number" class="col-sm-3">Aufgabennummer:</label>
                <div class="col-sm-9">
                    <div class="input-group">
                        {% with lecture.next_task_number as next_task_number %}
                        <input id="task_number" type="number" class="form-control" placeholder="#" maxlength="3"
                               value="{{ next_task_number }}" name="number" data-default="{{ next_task_number }}"
                               data-default="{{ next_task_number }}">
                        {% endwith %}
                        <span class="input-group-addon">
                            <label><input type="checkbox" id="no-number"> keine Nummer</label>
                        </span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="task_label" class="col-sm-3">Label:</label>
                <div class="col-sm-9">
                    <input id="task_label" type="text" class="form-control" placeholder="Label" maxlength="16"
                           value="{{ next_task_number }}" name="label" data-default="{{ next_task_number }}">
                </div>
            </div>
            <div class="form-group">
                <label for="task_number" class="col-sm-3">&nbsp;</label>
                <div class="col-sm-9">
                    <label>
                        <input type="checkbox" name="optional" value="optional"> optional
                    </label>
                    <input type="submit" class="btn btn-primary pull-right" value="erstellen">
                </div>
            </div>
        </form>
    {% endif %}
{% endblock %}